### ISSUE TITLE
error in ms_deformable_im2col_cuda

### ISSUE THREAD

**Issue by LANDDKPLA** [retsuh-bqw/SRFormer-Text-Det#10]
`error in ms_deformable_im2col_cuda: no kernel image is available for execution on the device.`
-------------------------------  ---------------------------------------------------------------------------------------
sys.platform                     linux
Python                             3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
numpy                             1.23.5
detectron2                       0.6 @/.../detectron2
Compiler                          GCC 9.4
CUDA compiler                CUDA 11.4
detectron2 arch flags       7.5
DETECTRON2_ENV_MODULE            <not set>
PyTorch                            1.13.1+cu116 @/.../torch
PyTorch debug build        False
torch._C._GLIBCXX_USE_CXX11_ABI  False
GPU available                   Yes
GPU 0                               NVIDIA RTX A6000 (arch=8.6)
Driver version                   535.86.10
CUDA_HOME                    /usr/local/cuda-11.4
TORCH_CUDA_ARCH_LIST             8.6
Pillow                               9.5.0
torchvision                       0.14.1+cu116 @/.../torchvision
torchvision arch flags       3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                               0.1.5.post20221221
iopath                               0.1.9
cv2                                   4.9.0
-------------------------------  ---------------------------------------------------------------------------------------

**Comment by LANDDKPLA** [comment]
<img width="742" alt="a9586d2cd51cf26685cd162c61ea01e" src="https://github.com/retsuh-bqw/SRFormer-Text-Det/assets/62082656/5214e164-9613-41cc-b120-28bc57ac7e3b">
I met this error before and I solve it by changing version of cuda and torch or setting "TORCH_CUDA_ARCH_LIST".
I've tried these method but of no use.
So how to solve this issue?

**Comment by LANDDKPLA** [comment]
I met this problem before and solved them by changing version of torch and setting "TORCH_CUDA_ARCH_LIST".
 I've tried these two methods today but of no use ...

**Comment by LANDDKPLA** [comment]
Solved by installing `MultiScaleDeformableAttention` following [Deformable-DETR](https://github.com/fundamentalvision/Deformable-DETR?tab=readme-ov-file) manually.

**Comment by retsuh-bqw** [comment]
Glad to hear! Thanks for the update and sharing.

> Solved by installing `MultiScaleDeformableAttention` following [Deformable-DETR](https://github.com/fundamentalvision/Deformable-DETR?tab=readme-ov-file) manually.
